// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumDetailDto = { id: string, title: string, artists: Array<ArtistRefDto>, albumType: string, releaseDate: string | null, cover: string | null, label: string | null, totalDurationMs: number, localCount: number, 
/**
 * Completo: un álbum rara vez pasa de 50 pistas y no se pagina.
 */
tracks: Array<TrackRowDto>, };

export type AlbumRowDto = { id: string, title: string, artistDisplay: string, year: number | null, 
/**
 * Identificador de la portada cacheada, o `null` si aún no lo está. El
 * frontend lo resuelve contra el protocolo `asset:`; la ruta en disco no
 * cruza el puente.
 */
cover: string | null, trackCount: number, localCount: number, };

/**
 * Error tal como lo ve el cliente.
 *
 * **No lleva texto para el usuario final**: lleva un código estable y una
 * clave i18n que el frontend traduce (ADR-012). Así el backend permanece
 * agnóstico del idioma y la API sirve a cualquier cliente.
 */
export type ApiError = { 
/**
 * Código estable. No cambia sin un `major` de la API.
 */
code: string, 
/**
 * Clave i18n del mensaje.
 */
messageKey: string, 
/**
 * Parámetros de interpolación del mensaje.
 */
params: Array<[string, string]>, 
/**
 * `true` si el usuario puede resolverlo desde Ajustes.
 */
actionable: boolean, 
/**
 * `true` si reintentar tiene sentido.
 */
retryable: boolean, 
/**
 * Detalle técnico. **Solo en compilaciones de depuración**: en release
 * podría filtrar rutas o fragmentos de credenciales a la interfaz.
 */
detail: string | null, };

export type ArtistDetailDto = { id: string, name: string, imageUrl: string | null, genres: Array<string>, localTrackCount: number, topTracks: Array<TrackRowDto>, albums: Array<AlbumRowDto>, };

/**
 * Referencia ligera a un artista.
 */
export type ArtistRefDto = { id: string, name: string, };

export type ArtistRowDto = { id: string, name: string, imageUrl: string | null, trackCount: number, localTrackCount: number, };

export type AudioDeviceDto = { id: string, name: string, isDefault: boolean, };

export type AudioSettingsDto = { 
/**
 * `0` desactiva el crossfade y activa la reproducción sin huecos.
 */
crossfadeMs: number, gapless: boolean, eqProfile: EqProfileDto, normalizeVolume: boolean, 
/**
 * `null` = dispositivo predeterminado del sistema.
 */
outputDeviceId: string | null, };

export type AudioSettingsInputDto = { crossfadeMs: number, gapless: boolean, eqProfile: EqProfileInputDto, normalizeVolume: boolean, outputDeviceId: string | null, };

/**
 * Disponibilidad local de una pista.
 */
export type AvailabilityDto = { "kind": "absent" } | { "kind": "downloading", progress: number, playable: boolean, } | { "kind": "local", format: string, bytes: bigint, } | { "kind": "failed", reasonKey: string, attempts: number, };

export type DownloadSettingsDto = { preferredFormat: string, 
/**
 * Descargas simultáneas por carril (inmediato y prefetch).
 */
maxConcurrent: number, maxRetries: number, };

export type EqProfileDto = { id: string, nameKey: string, gainsDb: Array<number>, };

export type EqProfileInputDto = { id: string, nameKey: string, gainsDb: Array<number>, };

/**
 * Una canción y sus otras versiones.
 *
 * El directo, la instrumental y la maqueta cuelgan de la grabación de estudio
 * en lugar de ocupar cada una su fila. La interfaz enseña `principal` y ofrece
 * desplegar `versiones`: no se esconde nada, se ordena.
 */
export type GrupoDeVersionesDto = { principal: TrackRowDto, versiones: Array<TrackRowDto>, };

export type HomeItemsDto = { "kind": "tracks", items: Array<TrackRowDto>, } | { "kind": "albums", items: Array<AlbumRowDto>, } | { "kind": "artists", items: Array<ArtistRowDto>, } | { "kind": "playlists", items: Array<PlaylistSummaryDto>, };

export type HomeSectionDto = { 
/**
 * Clave i18n del título, con sus parámetros: "Porque escuchaste {artist}".
 */
key: string, params: Array<[string, string]>, items: HomeItemsDto, };

export type IntegrationSettingsDto = { discordEnabled: boolean, discordClientId: string | null, lastfmEnabled: boolean, lastfmUser: string | null, 
/**
 * Solo de lectura: dice si hay sesión de Last.fm. Se ignora al recibirlo,
 * porque conectarse no es un ajuste que se cambie con un interruptor.
 */
lastfmConnected: boolean, };

/**
 * Lo que hace falta para el primer paso de la autenticación de Last.fm.
 *
 * El token no es un secreto: caduca en una hora y solo vale para esta
 * autorización. Viaja al frontend porque el segundo comando lo necesita y
 * guardarlo en el backend obligaría a mantener estado de una conversación que
 * puede quedarse a medias.
 */
export type LastfmAuthDto = { token: string, 
/**
 * Página de Last.fm donde el usuario autoriza la aplicación.
 */
url: string, };

export type LibraryStatsDto = { trackCount: bigint, 
/**
 * Cuántas están realmente en disco. Distinguirlo importa: el catálogo
 * incluye resultados de búsqueda que nunca se han descargado.
 */
localCount: bigint, albumCount: bigint, artistCount: bigint, totalDurationMs: bigint, totalBytes: bigint, };

/**
 * Todo lo que el backend comunica hacia el frontend.
 *
 * Enum exhaustivo a propósito: añadir un evento obliga a tocar aquí y a
 * regenerar los tipos, en lugar de colarse como una cadena suelta.
 */
export type LocalifyEvent = { "type": "trackChanged", trackId: string, source: string, } | { "type": "playStatusChanged", status: string, } | { "type": "seeked", trackId: string, positionMs: number, } | { "type": "volumeChanged", volume: number, } | { "type": "repeatModeChanged", mode: string, } | { "type": "shuffleChanged", enabled: boolean, } | { "type": "trackFinished", trackId: string, completed: boolean, msPlayed: number, } | { "type": "queueChanged", revision: bigint, } | { "type": "downloadStarted", trackId: string, } | { "type": "downloadPlayable", trackId: string, } | { "type": "downloadProgress", trackId: string, percent: number, } | { "type": "downloadCompleted", trackId: string, } | { "type": "downloadFailed", trackId: string, reasonKey: string, } | { "type": "availabilityChanged", trackId: string, availability: AvailabilityDto, } | { "type": "libraryChanged", scope: string, } | { "type": "playlistChanged", playlistId: string, kind: string, } | { "type": "playlistImportProgress", importId: string, done: number, total: number, } | { "type": "playlistImportFinished", importId: string, playlistId: string, } | { "type": "scanProgress", scanId: string, done: number, total: number, } | { "type": "searchRemoteReady", queryId: bigint, } | { "type": "settingsChanged", sections: Array<string>, } | { "type": "providerStatusChanged", provider: string, status: ProviderStatusDto, } | { "type": "libraryMoveProgress", moveId: string, done: number, total: number, } | { "type": "libraryPathChanged", path: string, } | { "type": "toast", level: string, messageKey: string, params: Array<[string, string]>, };

export type LyricLineDto = { atMs: number, text: string, };

export type LyricsDto = { 
/**
 * Si viene, la interfaz puede resaltar línea a línea.
 */
synced: Array<LyricLineDto> | null, plain: string | null, source: string, };

/**
 * Página de resultados.
 */
export type PageDto<T> = { items: Array<T>, 
/**
 * `null` cuando contar sería caro y no aporta. Solo viene en la primera
 * página; al seguir desplazándose, el cliente ya lo conoce.
 */
total: bigint | null, 
/**
 * `null` cuando no hay más resultados.
 */
nextCursor: string | null, };

/**
 * Petición de paginación.
 */
export type PageRequestDto = { offset: number, limit: number | null, cursor: string | null, };

/**
 * De dónde salió la reproducción. Determina qué suena después y qué texto
 * muestra el panel de cola.
 */
export type PlaybackContextDto = { "kind": "album", id: string, } | { "kind": "playlist", id: string, } | { "kind": "artist", id: string, } | { "kind": "liked" } | { "kind": "library" } | { "kind": "search", query: string, trackIds: Array<string>, } | { "kind": "recommendation", seedTrackId: string, trackIds: Array<string>, } | { "kind": "single" };

/**
 * Estado completo del reproductor.
 *
 * Es la respuesta de `player_get_state`, el comando de resincronización cuando
 * el frontend pierde eventos.
 */
export type PlayerStateDto = { track: TrackRowDto | null, status: string, positionMs: number, durationMs: number, 
/**
 * Cuánto hay decodificable. Solo difiere de `durationMs` durante una
 * descarga progresiva.
 */
bufferedMs: number, volume: number, repeat: string, shuffle: boolean, context: PlaybackContextDto | null, };

export type PlaylistDetailDto = { description: string | null, totalDurationMs: number, entries: Array<PlaylistEntryDto>, id: string, name: string, trackCount: number, 
/**
 * Álbumes cuyas portadas componen el mosaico, hasta cuatro.
 *
 * Identificadores, no rutas: el frontend los pide por `cover://` igual que
 * los de un álbum, y ninguna ruta de disco cruza el puente (ADR-018).
 */
coverAlbums: Array<string>, 
/**
 * `true` si el usuario eligió una imagen propia. Se pide entonces a
 * `cover://playlist/<id>` en lugar de componer el mosaico.
 */
hasOwnCover: boolean, updatedAt: bigint, source: string, };

export type PlaylistEntryDto = { 
/**
 * Identidad de la **entrada**, no de la pista: la misma canción puede
 * aparecer varias veces y "elimina esta fila" debe ser inequívoco.
 */
entryId: string, track: TrackRowDto, addedAt: bigint, };

export type PlaylistSummaryDto = { id: string, name: string, trackCount: number, 
/**
 * Álbumes cuyas portadas componen el mosaico, hasta cuatro.
 *
 * Identificadores, no rutas: el frontend los pide por `cover://` igual que
 * los de un álbum, y ninguna ruta de disco cruza el puente (ADR-018).
 */
coverAlbums: Array<string>, 
/**
 * `true` si el usuario eligió una imagen propia. Se pide entonces a
 * `cover://playlist/<id>` en lugar de componer el mosaico.
 */
hasOwnCover: boolean, updatedAt: bigint, source: string, };

/**
 * Posición y buffer. Se sondea varias veces por segundo, así que es
 * deliberadamente diminuto: emitirlo como evento saturaría el puente IPC.
 */
export type PositionDto = { positionMs: number, bufferedMs: number, };

/**
 * Lo que mejor responde a la consulta, sea del tipo que sea.
 *
 * Va etiquetado por tipo y no como tres campos opcionales: destacar dos cosas
 * a la vez no significa nada, y con campos sueltos el cliente tendría que
 * decidir a cuál hace caso.
 */
export type PrimeraCoincidenciaDto = { "kind": "track", "item": TrackRowDto } | { "kind": "album", "item": AlbumRowDto } | { "kind": "artist", "item": ArtistRowDto };

/**
 * Estado de un proveedor externo.
 */
export type ProviderStatusDto = { "state": "ready" } | { "state": "notConfigured" } | { "state": "unavailable", reasonKey: string, };

export type QueueEntryDto = { entryId: string, track: TrackRowDto, };

export type QueueSnapshotDto = { 
/**
 * Monótona: permite descartar respuestas obsoletas sin comparar contenido.
 */
revision: bigint, current: QueueEntryDto | null, 
/**
 * "Siguiente en la cola": prioridad absoluta, se consume al reproducirse.
 */
userQueue: Array<QueueEntryDto>, 
/**
 * Ventana de las siguientes del contexto, no el contexto entero.
 */
contextQueue: Array<QueueEntryDto>, context: PlaybackContextDto | null, 
/**
 * Clave i18n de "Siguiente desde: …".
 */
contextLabelKey: string | null, };

/**
 * Si el proveedor va a aportar algo más a la lista de canciones.
 *
 * Es una unión y no un `Option` porque los cuatro estados significan cosas
 * distintas para la interfaz: "no se preguntó" no es lo mismo que "está en
 * camino" ni que "el proveedor no responde".
 *
 * `Ready` no lleva canciones: ya están fundidas en `tracks`. Que vinieran del
 * proveedor o del catálogo no es asunto de quien las pinta.
 */
export type RemoteResultsDto = { "state": "notAttempted" } | { "state": "loading" } | { "state": "ready" } | { "state": "unavailable", reasonKey: string, };

export type SearchResultsDto = { 
/**
 * Monótono. El cliente descarta respuestas de pulsaciones ya superadas.
 */
queryId: bigint, 
/**
 * Lo que mejor responde, para destacarlo. `null` si no hay nada claro.
 */
top: PrimeraCoincidenciaDto | null, 
/**
 * Las canciones encontradas, ya ordenadas y agrupadas por versiones.
 */
tracks: Array<GrupoDeVersionesDto>, albums: Array<AlbumRowDto>, artists: Array<ArtistRowDto>, playlists: Array<PlaylistSummaryDto>, remote: RemoteResultsDto, };

export type SettingsDto = { language: string, libraryPath: string, 
/**
 * Catálogo de metadatos activo: `"ytmusic"` o `"spotify"`.
 */
metadataProvider: string, audio: AudioSettingsDto, download: DownloadSettingsDto, spotify: SpotifySettingsDto, integrations: IntegrationSettingsDto, ui: UiSettingsDto, };

/**
 * Modificación parcial. Solo los campos presentes se aplican.
 */
export type SettingsPatchDto = { language: string | null, metadataProvider: string | null, audio: AudioSettingsInputDto | null, download: DownloadSettingsDto | null, integrations: IntegrationSettingsDto | null, ui: UiSettingsDto | null, };

export type SpotifySettingsDto = { configured: boolean, 
/**
 * El `clientId` no es secreto y sirve para que el usuario reconozca cuál
 * puso. El `clientSecret` **nunca** aparece.
 */
clientId: string | null, };

/**
 * Detalle de una pista. Solo se pide al abrir una vista concreta.
 */
export type TrackDetailDto = { artists: Array<ArtistRefDto>, trackNumber: number | null, discNumber: number | null, isrc: string | null, releaseDate: string | null, addedAt: bigint, playCount: number, lastPlayedAt: bigint | null, id: string, title: string, artistDisplay: string, albumId: string | null, albumTitle: string | null, durationMs: number, availability: AvailabilityDto, isFavorite: boolean, explicit: boolean, 
/**
 * Segundos desde época en que la fila entró en **esta** lista, o `null` si
 * la lista no fecha sus filas. Ver [`TrackRow::added_at`].
 */
addedAt: bigint | null, };

export type TrackFilterDto = { favoritesOnly: boolean, 
/**
 * La vista Biblioteca lo activa; los resultados de búsqueda no.
 */
localOnly: boolean, albumId: string | null, artistId: string | null, genreId: bigint | null, text: string | null, };

/**
 * Fila de lista.
 *
 * Plana y estrecha a propósito: es lo que se serializa 50 000 veces al
 * recorrer la biblioteca, y cada campo de más se paga en cada scroll.
 */
export type TrackRowDto = { id: string, title: string, artistDisplay: string, albumId: string | null, albumTitle: string | null, durationMs: number, availability: AvailabilityDto, isFavorite: boolean, explicit: boolean, 
/**
 * Segundos desde época en que la fila entró en **esta** lista, o `null` si
 * la lista no fecha sus filas. Ver [`TrackRow::added_at`].
 */
addedAt: bigint | null, };

export type UiSettingsDto = { listDensity: string, startView: string, };
